// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tusrpdlbdgzegkieetwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1c3JwZGxiZGd6ZWdraWVldHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzczNjEsImV4cCI6MjA2MDMxMzM2MX0.hDm5eZ9OFDORQfz6QeoiO9ajbzI-03ZkgSe3RDcNfCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);